---
- name: Deploy a simple webpage
  hosts: all
  tasks:
    - name: Create install directory
      file:
        state: directory
        path: /var/www/html
        mode: 0755

    - name: Copy webpage from URL
      get_url:
        url: https://raw.githubusercontent.com/MathoAvito/Ansible-Exercise/main/Webfile/index.html
        dest: /var/www/html/index.html
        mode: 0755

    - name: install httpd package
      package:
        name: "httpd"
        state: present

    - name: Start and enable httpd service
      service:
        name: "httpd"
        state: started
        enabled: true
